### ISSUE TITLE
Скараціць "пераўсталяваць" ці замяніць яго, бо вялізнае

### ISSUE THREAD

**Issue by MaryAlex** [Ludeon/RimWorld-Belarusian#40]
![image](https://github.com/Ludeon/RimWorld-Belarusian/assets/15628733/5944caf1-737b-460d-b82b-33652ec7280a)

**Comment by SampleText2k77** [comment]
Папраўлю у #39

**Comment by MaryAlex** [comment]
А, добра, я думала гэта мой пераклад быў
